# Git Setup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Data Preprocessing

In [ ]:
import pandas as pd

###Load the data

source: World Bank

In [ ]:
def load_csv_data():
    
    data_file = pd.read_csv("/content/drive/MyDrive/DOPP_2020/Data_indicators1.csv", sep=',')

    return data_file

data = load_csv_data()

In [ ]:
data

In [ ]:
data.tail(15)

                                                   Time  ... Central government debt, total (% of GDP) [GC.DOD.TOTL.GD.ZS]
13227                                              2020  ...                                                 ..
13228                                              2020  ...                                                 ..
13229                                              2020  ...                                                 ..
13230                                              2020  ...                                                 ..
13231                                              2020  ...                                                 ..
13232                                              2020  ...                                                 ..
13233                                              2020  ...                                                 ..
13234                                              2020  ...                                                 ..
13235                                              2020  ...                                                 ..
13236                                              2020  ...                                                 ..
13237                                               NaN  ...                                                NaN
13238                                               NaN  ...                                                NaN
13239                                               NaN  ...                                                NaN
13240  Data from database: World Development Indicators  ...                                                NaN
13241                          Last Updated: 12/16/2020  ...                                                NaN

[15 rows x 17 columns]

### Drop unnecessary rows and columns

In [ ]:
#drop rows
data.drop(data.tail(5).index,inplace=True)
#drop columns
data.drop(['Time Code','Country Code'], axis = 1, inplace=True)
#rename column Time to Year
data.rename(columns={"Time": "Year"},inplace = True)

In [ ]:
#data.tail(15)

### Set index

In [ ]:
data = data.set_index(["Country Name","Year"])
data

                           GNI per capita, Atlas method (current US$) [NY.GNP.PCAP.CD]  ... Central government debt, total (% of GDP) [GC.DOD.TOTL.GD.ZS]
Country Name          Year                                                              ...
Argentina             1960                                                 ..           ...                                                 ..
Australia             1960                                                 ..           ...                                                 ..
Brazil                1960                                                 ..           ...                                                 ..
China                 1960                                                 ..           ...                                                 ..
France                1960                                                 ..           ...                                                 ..
...                                                                       ...           ...                                                ...
Samoa                 2020                                                 ..           ...                                                 ..
San Marino            2020                                                 ..           ...                                                 ..
Sao Tome and Principe 2020                                                 ..           ...                                                 ..
Senegal               2020                                                 ..           ...                                                 ..
Serbia                2020                                                 ..           ...                                                 ..

[13237 rows x 13 columns]

In [ ]:
#drop Year 2020 since too little data available
data.drop('2020',level='Year',inplace=True)
data

                           GNI per capita, Atlas method (current US$) [NY.GNP.PCAP.CD]  ... Central government debt, total (% of GDP) [GC.DOD.TOTL.GD.ZS]
Country Name          Year                                                              ...
Argentina             1960                                                 ..           ...                                                 ..
Australia             1960                                                 ..           ...                                                 ..
Brazil                1960                                                 ..           ...                                                 ..
China                 1960                                                 ..           ...                                                 ..
France                1960                                                 ..           ...                                                 ..
...                                                                       ...           ...                                                ...
Samoa                 2019                                               4190           ...                                                 ..
San Marino            2019                                                 ..           ...                                                 ..
Sao Tome and Principe 2019                                               1930           ...                                                 ..
Senegal               2019                                               1460           ...                                                 ..
Serbia                2019                                               7030           ...                                                 ..

[13020 rows x 13 columns]

### Extract dataset

In [ ]:
dataset1 = data["GNI per capita, Atlas method (current US$) [NY.GNP.PCAP.CD]"]
dataset1

Country Name           Year
Argentina              1960    ..
Australia              1960    ..
Brazil                 1960    ..
China                  1960    ..
France                 1960    ..
                               ..
Samoa                  2020    ..
San Marino             2020    ..
Sao Tome and Principe  2020    ..
Senegal                2020    ..
Serbia                 2020    ..
Name: GNI per capita, Atlas method (current US$) [NY.GNP.PCAP.CD], Length: 13237, dtype: object

# Frage 1

In [ ]:
#load thresholds
def load_csv_income_thresholds():
    
    data_file = pd.read_csv("/content/drive/MyDrive/DOPP_2020/Data_indicators1.csv", sep=',')

    return data_file

income_thresholds = load_csv_income_thresholds()

count     13237
unique     2344
top          ..
freq       4668
Name: GNI per capita, Atlas method (current US$) [NY.GNP.PCAP.CD], dtype: object